#include "report.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <iostream>
#include <algorithm>
#include <cstdlib>

// ─── Métricas ──────────────────────────────────────────────────────────────────

int totalMovement(const vector <int> &path){
    int total = 0;
    for(int i = 1; i < path.size(); ++i)
        total += abs(path[i] - path[i - 1]);
    return total;
}

double avgSeek(const vector <int> &path){
    if(path.size() < 2)
        return 0.0;
    return static_cast <double> (totalMovement(path)) / (path.size() - 1);
}

int maxJump(const vector <int> &path){
    int best = 0;
    for(int i = 1; i < path.size(); ++i)
        best = max(best, std::abs(path[i] - path[i - 1]));
    return best;
}

vector <int> cumulativeMovement(const vector <int> &path){
    vector <int> cum;
    cum.reserve(path.size());
    int total = 0;
    cum.push_back(0);
    for(int i = 1; i < path.size(); ++i){
        total += abs(path[i] - path[i - 1]);
        cum.push_back(total);
    }
    return cum;
}

// ─── Utilidades internas ───────────────────────────────────────────────────────

static string toJsArray(const vector <int> & v){
    ostringstream oss;
    oss << "[";
    for(int i = 0; i < v.size(); ++i){
        if (i) oss << ",";
        oss << v[i];
    }
    oss << "]";
    return oss.str();
}

static vector <int> sample(const vector <int> &v, int n){
    if(v.size() <= n) return v;
    vector <int> s;
    s.reserve(n);
    double step = static_cast <double> (v.size() - 1) / (n - 1);
    for(int i = 0; i < n; ++i)
        s.push_back(v[static_cast <int> (i * step)]);
    return s;
}

// ─── Escritura de data.js ──────────────────────────────────────────────────────

void writeDataJS(const string &filename, int initialHead, int numRequests, int maxCylinder, const vector <int> &pathFcfs, const vector <int> &pathScan, const vector <int> &pathCscan){
    int tFp = totalMovement(pathFcfs), tSp = totalMovement(pathScan), tCp = totalMovement(pathCscan);
    double aFp = avgSeek(pathFcfs), aSp = avgSeek(pathScan), aCp = avgSeek(pathCscan);
    int mFp = maxJump(pathFcfs), mSp = maxJump(pathScan), mCp = maxJump(pathCscan);

    vector <int> cumFp = cumulativeMovement(pathFcfs);
    vector <int> cumSp = cumulativeMovement(pathScan);
    vector <int> cumCp = cumulativeMovement(pathCscan);

    const int sampleSize = 300;
    vector <int> sFp  = sample(pathFcfs, sampleSize);
    vector <int> sSp  = sample(pathScan, sampleSize);
    vector <int> sCp  = sample(pathCscan, sampleSize);
    vector <int> scFp = sample(cumFp, sampleSize);
    vector <int> scSp = sample(cumSp, sampleSize);
    vector <int> scCp = sample(cumCp, sampleSize);

    ofstream out(filename);
    if(!out){
        cerr << "Error: no se pudo crear " << filename << "\n";
        return;
    }

    out << fixed << setprecision(2);

    out << "// Generated by scheduler - do not edit manually\n";
    out << "const INITIAL_HEAD = " << initialHead  << ";\n";
    out << "const NUM_REQUESTS = " << numRequests  << ";\n";
    out << "const MAX_CYLINDER = " << maxCylinder  << ";\n\n";

    out << "const TOTALS    = [" << tFp << ","  << tSp << ","  << tCp << "];\n";
    out << "const AVERAGES  = [" << aFp << ","  << aSp << ","  << aCp << "];\n";
    out << "const MAX_JUMPS = [" << mFp << ","  << mSp << ","  << mCp << "];\n\n";

    out << "const PATH_FCFS = " << toJsArray(sFp)  << ";\n";
    out << "const PATH_SCAN = " << toJsArray(sSp)  << ";\n";
    out << "const PATH_CSCAN = " << toJsArray(sCp)  << ";\n\n";

    out << "const CUM_FCFS  = " << toJsArray(scFp) << ";\n";
    out << "const CUM_SCAN  = " << toJsArray(scSp) << ";\n";
    out << "const CUM_CSCAN = " << toJsArray(scCp) << ";\n";

    out.close();
    cout << "  → " << filename << " generado correctamente.\n";
}